#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorks2017")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleApp1.Properties.Settings.Default.AdventureWorks2017ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspGetBillOfMaterials")]
		public ISingleResult<uspGetBillOfMaterialsResult> uspGetBillOfMaterials([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartProductID", DbType="Int")] System.Nullable<int> startProductID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckDate", DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startProductID, checkDate);
			return ((ISingleResult<uspGetBillOfMaterialsResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspGetBillOfMaterialsResult
	{
		
		private System.Nullable<int> _ProductAssemblyID;
		
		private System.Nullable<int> _ComponentID;
		
		private string _ComponentDesc;
		
		private System.Nullable<decimal> _TotalQuantity;
		
		private System.Nullable<decimal> _StandardCost;
		
		private System.Nullable<decimal> _ListPrice;
		
		private System.Nullable<short> _BOMLevel;
		
		private System.Nullable<int> _RecursionLevel;
		
		public uspGetBillOfMaterialsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductAssemblyID", DbType="Int")]
		public System.Nullable<int> ProductAssemblyID
		{
			get
			{
				return this._ProductAssemblyID;
			}
			set
			{
				if ((this._ProductAssemblyID != value))
				{
					this._ProductAssemblyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentID", DbType="Int")]
		public System.Nullable<int> ComponentID
		{
			get
			{
				return this._ComponentID;
			}
			set
			{
				if ((this._ComponentID != value))
				{
					this._ComponentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComponentDesc", DbType="NVarChar(50)")]
		public string ComponentDesc
		{
			get
			{
				return this._ComponentDesc;
			}
			set
			{
				if ((this._ComponentDesc != value))
				{
					this._ComponentDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalQuantity", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> TotalQuantity
		{
			get
			{
				return this._TotalQuantity;
			}
			set
			{
				if ((this._TotalQuantity != value))
				{
					this._TotalQuantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardCost", DbType="Money")]
		public System.Nullable<decimal> StandardCost
		{
			get
			{
				return this._StandardCost;
			}
			set
			{
				if ((this._StandardCost != value))
				{
					this._StandardCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListPrice", DbType="Money")]
		public System.Nullable<decimal> ListPrice
		{
			get
			{
				return this._ListPrice;
			}
			set
			{
				if ((this._ListPrice != value))
				{
					this._ListPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOMLevel", DbType="SmallInt")]
		public System.Nullable<short> BOMLevel
		{
			get
			{
				return this._BOMLevel;
			}
			set
			{
				if ((this._BOMLevel != value))
				{
					this._BOMLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecursionLevel", DbType="Int")]
		public System.Nullable<int> RecursionLevel
		{
			get
			{
				return this._RecursionLevel;
			}
			set
			{
				if ((this._RecursionLevel != value))
				{
					this._RecursionLevel = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
